# opentelemetry-collector/values.yaml
# DaemonSet deployment to receive traces and forward to Tempo.

mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.102.1

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  exporters:
    otlp:
      endpoint: tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [otlp]

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
