# Main Terraform configuration for K3s on-premises platform
# Simplified configuration for hybrid deployment approach

terraform {
  required_version = ">= 1.5.0"
  
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.11"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.23"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}

# Local values and configuration
locals {
  cluster_name = var.cluster_name
  namespace    = "k3s-platform"
  
  # Network configuration
  network_cidr = var.network_cidr
  metallb_pool = var.metallb_pool
  
  # K3s version
  kubernetes_version = var.kubernetes_version
  
  # Paths
  kubeconfig_path = "${path.root}/kubeconfig"
  
  # All nodes
  all_nodes = merge(var.control_plane_nodes, var.worker_nodes)
}

# Generate cluster secrets
# Note: K3s secrets will be generated by the PowerShell script
resource "random_password" "argocd_admin" {
  length  = 16
  special = true
}

# Create namespaces using kubectl
resource "null_resource" "create_namespaces" {
  provisioner "local-exec" {
    command = "kubectl create namespace platform --dry-run=client -o yaml | kubectl apply -f -"
  }
  
  provisioner "local-exec" {
    command = "kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -"
  }
  
  provisioner "local-exec" {
    command = "kubectl create namespace security --dry-run=client -o yaml | kubectl apply -f -"
  }
  
  provisioner "local-exec" {
    command = "kubectl create namespace velero --dry-run=client -o yaml | kubectl apply -f -"
  }
  
  provisioner "local-exec" {
    command = "kubectl create namespace vault --dry-run=client -o yaml | kubectl apply -f -"
  }
}

# MetalLB module
module "metallb" {
  source = "./modules/metallb"
  
  depends_on = [
    null_resource.create_namespaces
  ]
  
  metallb_namespace = "metallb-system"
  
  metallb_config = {
    address_pools = [
      {
        name = "default"
        protocol = "layer2"
        addresses = [local.metallb_pool]
      }
    ]
  }
}

# ArgoCD module
module "argocd" {
  source = "./modules/argocd"
  
  depends_on = [
    module.metallb,
    null_resource.create_namespaces
  ]
  
  argocd_namespace = "argocd"
  
  argocd_helm_config = {
    repository = "https://argoproj.github.io/argo-helm"
    chart      = "argo-cd"
    version    = "v5.53.0"
  }
  
  argocd_values = {
    server = {
      service = {
        type = "LoadBalancer"
        loadBalancerIP = "192.168.56.240"
        ports = {
          http = 80
          https = 443
        }
        annotations = {
          "metallb.universe.tf/address-pool" = "default"
        }
      }
      config = {
        repositories = {
          talos_platform = {
            url = "https://github.com/dmitr166/talos_platform.git"
          }
        }
        "application.resourceTrackingMethod" = "annotation"
        "timeout.reconciliation" = "180s"
      }
    }
    notifications = {
      enabled = true
    }
    dex = {
      enabled = false
    }
  }
}

# Wait for services to be ready
resource "null_resource" "wait_services_ready" {
  depends_on = [
    module.metallb,
    module.argocd
  ]
  
  provisioner "local-exec" {
    command = "kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=metallb -n metallb-system --timeout=300s"
  }
  
  provisioner "local-exec" {
    command = "kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=argocd-server -n argocd --timeout=300s"
  }
}
